image: ruby:2.4.2

stages:
  - build
  - test
  - review
  - stage
  - prod

variables:
  DATABASE_URL: 'mongodb://mongo/user_posts'

before_script:
  - cd reddit
  - bundle install

build_job:
  stage: build
  script:
    - echo 'Building'

test_unit_job:
  stage: test
  services:
    - mongo:latest
  script:
    - ruby simpletest.rb

test_integration_job:
  stage: test
  script:
    - echo 'Testing 2'

deploy_dev_job:
  stage: review
  script:
    - echo 'Deploy'
  environment:
    name: dev
    url: http://dev.example.com

staging:
  stage: stage
  when: manual
  script:
    - echo 'Deploy on staging'
  environment:
    name: beta
    url: http://beta.eample.com

production:
  stage: prod
  when: manual
  script:
    - echo 'Deploy on production'
  environment:
    name: production
    url: http://eample.com
