image: ruby:2.4.2

stages:
  - build
  - test
  - review
  - stage
  - production

variables:
  DATABASE_URL: 'mongodb://mongo/user_posts'
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DOCKER_IMAGE: 'oleksiihead/otus-reddit'

before_script:
  - cd reddit
  - bundle install

build_job:
  stage: build
  image: docker:20.10.5
  services:
    - docker:dind
  before_script:
    - docker info
    - echo "${DOCKER_REGISTRY_PASS}" | docker login -u ${DOCKER_REGISTRY_USER} --password-stdin
  script:
    - echo 'Building image'
    - docker build -t ${DOCKER_IMAGE}:${CI_COMMIT_REF_NAME} -t ${DOCKER_IMAGE}:${CI_COMMIT_SHORT_SHA} ./redit/.
    - docker push ${DOCKER_IMAGE}:${CI_COMMIT_REF_NAME}
    - docker push ${DOCKER_IMAGE}:${CI_COMMIT_SHORT_SHA}

test_unit_job:
  stage: test
  services:
    - mongo:latest
  script:
    - ruby simpletest.rb

test_integration_job:
  stage: test
  script:
    - echo 'Testing 2'

deploy_dev_job:
  stage: review
  script:
    - echo 'Deploy'
  environment:
    name: dev
    url: http://dev.example.com

branch review:
  stage: review
  image: docker:20.10.5
  services:
    - docker:dind
  before_script:
    - docker info
    - echo "${DOCKER_REGISTRY_PASS}" | docker login -u ${DOCKER_REGISTRY_USER} --password-stdin
  script:
    - echo "Deploy to $CI_ENVIRONMENT_SLUG"
    - docker run -d ${DOCKER_IMAGE}:${CI_COMMIT_SHORT_SHA}
  environment:
    name: branch/$CI_COMMIT_REF_NAME
    url: http://$CI_ENVIRONMENT_SLUG.example.com
  only:
    - branches
  except:
    - master

staging:
  stage: stage
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy staging'
  environment:
    name: beta
    url: http://beta.example.com

production:
  stage: production
  when: manual
  script:
    - echo 'Deploy prod'
  environment:
    name: production
    url: http://example.com
